files=(
  "$(brew --prefix)/etc/profile.d/bash_completion.sh"
  "${HOME}/.bash_aliases"
  "${HOME}/.export"
  "${HOME}/.private"
)
for file in ${files[@]}; do
  if [ -r $file ]; then
    source $file
  fi
done

bind '"\eh":backward-char'
bind '"\ej":history-search-forward'
bind '"\ek":history-search-backward'
bind '"\el":forward-char'

sysctl machdep.xcpm.cpu_thermal_level
