# adb
alias adbs='adb shell screencap -p | perl -pe "s/\x0D\x0A/\x0A/g" > screen.png'
alias adbp='adb shell input keyevent KEYCODE_WAKEUP;adb shell input swipe 500 1500 500 500'

# custom
alias p='ping www.google.com'
alias rp='rsync -aP'

# ls
alias la='ls -Ad .*'
alias ll='ls -lFh'
alias lla='ls -AdlhSr .*'

# grep
temp='grep'
temp="$temp --binary-files=without-match"
temp="$temp --color=auto"
temp="$temp --exclude-dir=.git"
temp="$temp --exclude-dir=.npm"
temp="$temp --exclude-dir=logs"
temp="$temp --exclude-dir=node_modules"
temp="$temp --exclude=*.map"
temp="$temp --exclude=.luacheckcache"
alias grep=$temp
alias ggrep='ggrep --color=auto'

# xclip
alias xi='xclip -i -selection clipboard'
