export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
if [ -f "$HOME"/.bashrc ]; then
	source "$HOME"/.bashrc
fi
if [ -f "$HOME"/.bash_aliases ]; then
	source "$HOME"/.bash_aliases
fi
if [ -f "$HOME"/github/QimatLuo/Setting/git/git-completion.bash ]; then
  source "$HOME"/github/QimatLuo/Setting/git/git-completion.bash
fi
if [ -f "$HOME"/github/QimatLuo/Setting/tmux/bash_completion_tmux.sh ]; then
  source "$HOME"/github/QimatLuo/Setting/tmux/bash_completion_tmux.sh
fi
if [ -f "$HOME"/.export ]; then
  source "$HOME"/.export
fi
if [ -f "$HOME"/.bash_private ]; then
  source "$HOME"/.bash_private
fi
