export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
source "$HOME"/.bashrc
source "$HOME"/.bash_aliases
if [ -f "$HOME"/github/QimatLuo/Setting/git/git-completion.bash ]; then
  source "$HOME"/github/QimatLuo/Setting/git/git-completion.bash
fi
if [ -f "$HOME"/github/QimatLuo/Setting/tmux/bash_completion_tmux.sh ]; then
  source "$HOME"/github/QimatLuo/Setting/tmux/bash_completion_tmux.sh
fi
if [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi
if [ -f "$HOME"/.export ]; then
  source "$HOME"/.export
fi
export PATH="$PATH:$HOME/Library/Python/2.7/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/
export PS1="\[\033[0;37m\]\d \t \W\$ \[\033[0m\]"
export GPG_TTY=$(tty)
