" Vundle {===
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

" vim-snipmate
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'

Plugin 'editorconfig/editorconfig-vim'

Plugin 'leafgarland/typescript-vim'

Plugin 'posva/vim-vue'
Plugin 'michaeljsmith/vim-indent-object'
Plugin 'infoslack/vim-docker'

call vundle#end()
filetype plugin indent on
" ===} Vundle

set noeol
set colorcolumn=81
set encoding=utf-8
set hlsearch
set ruler
set ignorecase
set incsearch
set nowrap
set relativenumber
set shiftwidth=2
set tabstop=2
set expandtab
set t_Co=256
set synmaxcol=250
if &diff
	set background=light
else
	set background=dark
endif

syntax on

so ~/github/QimatLuo/Setting/vim/map.vim
so ~/github/QimatLuo/Setting/vim/highlight.vim
so ~/github/QimatLuo/Setting/vim/DiffText.vim
so ~/github/QimatLuo/Setting/vim/GitMergetool.vim
so ~/github/QimatLuo/Setting/vim/tabline.vim
so ~/github/QimatLuo/Setting/vim/osx.vim
